apiVersion: apps/v1
kind: Deployment
metadata:
  name: middle-service
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: middle-service
  template:
    metadata:
      labels:
        app: hero
    spec:
      containers:
        - name: telegram-bot
          image: normat/middle-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8082