apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegram-bot
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegram-bot
  template:
    metadata:
      labels:
        app: hero
    spec:
      containers:
        - name: telegram-bot
          image: normat/telegram-bot
          imagePullPolicy: Always
          ports:
            - containerPort: 8081